src/agua/urls.py
from django.urls import path, register_converter

from . import views, converters

register_converter(converters.MonthYearConverter, 'mmyyyy')

app_name = 'agua'
urlpatterns = [
    path('', views.agua_list, name='agua_list'),
    path('new', views.agua_create, name='agua_new'),
    path('view/<int:pk>', views.agua_view, name="agua_view"),
    path('edit/<int:pk>', views.agua_update, name="agua_edit"),
    path('delete/<int:pk>', views.agua_delete, name="agua_delete"),
    path('consumo/<int:pk>', views.consumo, name="consumo"),
    path('demonstrativo', views.demonstrativo, name="demonstrativo"),
    path('demonstrativo/<mmyyyy:competencia>/', views.demonstrativo, name="demonstrativo"),

]

src/aguaapp/urls.py
from django.urls import path

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from agua import views as agua_views

urlpatterns = [
    url(r'^$', agua_views.home, name='home'),
    url( r'^login/$',auth_views.LoginView.as_view(template_name="home.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^settings/$', agua_views.settings, name='settings'),
    url(r'^settings/password/$', agua_views.password, name='password'),
    url(r'^signup/$', agua_views.signup, name='signup'),
    path('admin/', admin.site.urls),
    path('agua/',include('agua.urls')),
]

src/bkp/agua/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
import profiles.urls
import accounts.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = 'Agua Administração'
admin.site.site_header = 'Agua Administração'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('users/', include(profiles.urls)),
    path('admin/', admin.site.urls),
    path('', include(accounts.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

src/agua/views.py
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib import messages

from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import ModelForm, DateInput, Textarea , TextInput

from agua.models import Condominio, Condomino, Hidrometro, Medicao, TipoDespesa, Despesa,Competencia
from django.utils.translation import ugettext_lazy as _

from social_django.models import UserSocialAuth

import logging
import json

class DateInput(DateInput):
    input_type = 'date'

class TelInput(TextInput):
    input_type = 'tel'

class EmailInput(TextInput):
    input_type = 'email'


class MedicaoForm(ModelForm):
    class Meta:
        model = Medicao
        fields = ['hidrometro' ,
                  'data_medicao' ,
                  'cmpt' ,
                  'medicao' ]
        help_texts = {
            'nome_conhecido': _('Informe o nome ou apelido pelo qual é conhecido'),
            'vira_para_o_encontro': _('Informe se virá para o encontro'),

        }
        labels = {
            'hidrometro': _('Hidrometro'),
            'ndata_medicao': _('Data da medicao'),
            'competencia': _('Competencia'),
            'medicao': _('Medicao'),

        }
        error_messages = {
            'nome_conhecido': {
                'max_length': _("O nome está muito comprido."),
            },
        }
        widgets = {
           'nome_conhecido': TextInput(attrs={'size':'20'}),
           'nome_commpleto': TextInput(attrs={'size':'80'}),
           'email': EmailInput(attrs={'size':'80'}),
           'data_nascimento': DateInput(),
           'telefone': TelInput(attrs={'placeholder':'61-99635-6601'}),
           'cep_correspondencia': TextInput(attrs={'placeholder':'80000-000'}),
           'comentario': Textarea(attrs={'rows':4,'cols':50})
        }
        exclude = ['usuario_responsavel']
"""
    usuario_responsavel = models.ForeignKey(settings.AUTH_USER_MODEL,
      null=True, blank=True, on_delete=models.SET_NULL)
    nome_conhecido = models.CharField(max_length=55)
    nome_completo = models.CharField(max_length=200)
    vira_para_o_encontro = models.BooleanField()
    telefone = models.CharField(max_length=20,blank=True)
    parentesco = models.CharField(max_length=20,
    choices=PARENTESCO_CHOICES,
    default='Outro')
    email = models.EmailField(max_length=254,blank=True)
    data_nascimento = models.DateField(auto_now=False,auto_now_add=False)
    endereco_correspondencia = models.CharField(max_length=200,blank=True)
    cep_correspondencia = models.CharField(max_length=9,blank=True)
    cidade_correspondencia = models.CharField(max_length=100,blank=True)
    estado_correspondencia = models.CharField(max_length=2,blank=True)
    comentario = models.CharField(max_length=512,blank=True)
"""
    # def __init__(self, *args, **kwargs):
    #    self.request = kwargs.pop('request', None)
    #    return super(AguaForm, self).__init__(*args, **kwargs)

    # def save(self, *args, **kwargs):
    #     kwargs['commit']=False
    #     obj = super(AguaForm, self).save(*args, **kwargs)
    #     if self.request:
    #         obj.usuario_responsavel = self.request.user
    #     obj.save()
    #     return obj

    # def __init__(self,user,*args, **kwargs):
    #      self.request = kwargs.pop('request')
    #      return super(PatientForm,self).__init__(*args,**kwargs)
    #
    #
    # def save(self, *args, **kwargs):
    #     kwargs['commit'] = False
    #     obj = super(Agua_Form.self).save(*args,**kwargs)
    #     if self.request:
    #         obj.usuario_responsaavel = self.request.user
    #     obj.save()
@login_required
def home(request,template_name='agua/home.html'):

    try:
        condomino = Condomino.objects.get(usuario=request.user.id)
    except Condomino.DoesNotExist:
        condomino = None

    listaHidrometros=[]
    condominos = []

    if request.user.is_superuser:
        # Admin, pode tudo
        condominos  = Condomino.objects.all()
    else:
        if request.user.groups.filter(name='gerente').count():
            # Gerente - Todos do condominio
            if condomino:
                condominos = Condomino.objects.filter(condominio=condomino.condominio.id)
        else:
            # Não é gerente - Pega somente o seu.
            condominos = Condomino.objects.filter(pk=condomino.id)



    for condomino in condominos:
        hidrometros = Hidrometro.objects.filter(condomino=condomino.id)
        listaHidrometros.append([condomino,hidrometros])

    return render(request, template_name , {'listaHidrometros':listaHidrometros, 'condomino': condomino})

@login_required
def demonstrativo(request, competencia=None , template_name='agua/demonstrativo.html'):

    condominio = 1
    cpt = None
    if competencia != None:
        comp=str(competencia).zfill(6)
        ano = int(comp[-4:])
        mes = int(comp[:2])
        cpt = Competencia.objects.filter(condominio__id = 1 ,
                                         competencia__year = ano ,
                                         competencia__month = mes)[0]

    if cpt == None:
        cpt = Competencia.objects.latest()


    despesas = Despesa.objects.filter(condominio__id=condominio , cmpt__id=cpt.id)
    valor_total_despesa = 0
    for despesa in despesas:
        valor_total_despesa += despesa.valor

    consumos = Medicao.objects.filter(hidrometro__condomino__condominio__id=condominio , cmpt__id=cpt.id).order_by("hidrometro__condomino__nome_conhecido","hidrometro__identificacao")
    total_consumo = 0
    consumos_data = []
    for consumo in consumos:
        total_consumo += consumo.consumo
        consumos_data.append([consumo,0,0])

    consumo_por_condomino = {}
    for consumo in consumos_data:
        consumo[1] =  (  consumo[0].consumo / total_consumo * 100 )
        consumo[2] = consumo[1] / 100 * valor_total_despesa
        nome = consumo[0].hidrometro.condomino.nome_conhecido
        if not nome in consumo_por_condomino:
            consumo_por_condomino[nome] = [nome , consumo[0].consumo , consumo[1] , consumo[2] ]
        else:
            consumo_por_condomino[nome][1] += consumo[0].consumo
            consumo_por_condomino[nome][2] += consumo[1]
            consumo_por_condomino[nome][3] += consumo[2]

    competencias = Competencia.objects.filter(condominio__id=condominio).order_by('-competencia')

    return render(request,template_name,{   'competencia':cpt,
                                            'despesas':despesas ,
                                            'valor_total_despesa': valor_total_despesa ,
                                            'consumos':consumos_data ,
                                            'total_consumo': total_consumo ,
                                            'competencias': competencias ,
                                            'consumo_por_condomino': consumo_por_condomino.values()})

@login_required
def consumo(request, hidrometro , template_name='agua/consumo.html'):
    hidrometro = get_object_or_404(Hidrometro, pk=pk)
    competencias = Competencia.objects.filter(situacao=Competencia.ABERTO)
    form = MedicaoForm(request.POST or None, instance=hidrometro)
    if form.is_valid():
        form.save()
        return redirect('/agua/')
    return render(request, template_name, {'form':form})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            #login(request, user,backend='django.contrib.auth.backends.ModelBackend)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html',{'form': form})


@login_required
def settings(request):
    user = request.user

    # try:
    #     github_login = user.social_auth.get(provider='github')
    # except UserSocialAuth.DoesNotExist:
    #     github_login = None

    # try:
    #     twitter_login = user.social_auth.get(provider='twitter')
    # except UserSocialAuth.DoesNotExist:
    #     twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'settings.html', {
        # 'github_login': github_login,
        # 'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })

@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'agua/password.html', {'form': form})


@login_required
def agua_list(request, template_name='agua/agua_list.html'):
    logger = logging.getLogger('testlogger')
    logger.info('agua_list')

src/bkp/agua/views.py
from django.views import generic


class HomePage(generic.TemplateView):
    template_name = "home.html"


class AboutPage(generic.TemplateView):
    template_name = "about.html"

src/aguaapp/templates/agua/agua_confirm_delete.html
{% extends 'base.html' %}
{% block menu %}<li><a href="admin">Admin</a></li>{% endblock %}

{% block content %}
<h1>Apagar</h1>
<form method="post">{% csrf_token %}
    Vocë tem certeza que deseja apagar "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

src/aguaapp/templates/agua/agua_detail.html
{% extends 'base.html' %}
{% block menu %}<li><a href="admin">Admin</a></li>{% endblock %}

{% block content %}
<h1>Detalhes</h1>
<h2>Nome/Apeido: {{object.nome_conhecido}}</h2>
Nome completo: {{object.nome_completo}}<br/>
Telefone: {{ object.telefone }}<br/>
{% if object.vira_para_o_encontro %}
   Virá para o encontro<br/>
{% else %}
  Não Virá para o encontro<br/>
{% endif %}
Parentesco: {{ object.parentesco}}<br/>
Email: {{ object.email }} <br/>
Data de Nascimento: {{ object.data_nascimento }}<br/>
Endereço: {{ object.endereco_correspondencia }}<br/>
CEP: {{ object.cep_correspondencia }}<br/>
Cidade: {{ object.cidade_correspondencia }}<br/>
Estado: {{ object.estado_correspondencia }}<br/>
Comentario: {{ object.comentario }} <br/>
{% endblock %}

src/aguaapp/templates/agua/agua_form.html
{% extends 'base.html' %}
{% block menu %}<li><a href="admin">Admin</a></li>{% endblock %}

{% block content %}
<h1>Criar</h1>
{% if obs %}
<div class="alert alert-warning">
   {{ obs }}
</div>
{% endif %}
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit"/>

{% for message in messages %}
  <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
       {{ message }}
   </div>
 {% endfor %}

{% if form.errors %}
   {% for erro in form.errors %}
    <div class="alert alert-error"0>
          {{ erro }}
    </div>
   {% endfor%}
{% endif %}

{% endblock %}

src/aguaapp/templates/agua/agua_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Agua</h1>
<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nome Completo</th>
      <th>Telefone</th>
      <th>Ver</th>
      <th>Alterar</th>
      <th>Deletar</th>
    </tr>
  </thead>
  <tbody>
    {% for agua in object_list %}
    <tr>
      <td>{{ agua.nome_conhecido }}</td>
      <td>{{ agua.nome_completo }}</td>
      <td>{{ agua.telefone }}</td>
      <td><a href="/agua/view/{{ agua.id }}"><span class="glyphicon glyphicon-eye-open"/> Ver</span> </a></td>
      <td><a href="/agua/edit/{{ agua.id }"><span class="glyphicon glyphicon-pencil"/> Alterar</span> </a></td>
      <td><a href="/agua/delete/{{ agua.id }}"><span class="glyphicon glyphicon-trash"/> Deletar</span> </a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="/agua/new">Cadastrar Nova Parente</a>
{% endblock %}

src/aguaapp/templates/agua/consumo.html
{% extends 'base.html' %}

{% block scripthead %}
<script type="text/javascript">
   $(document).ready(function() {
     $(function() {
          // navigate to page on click event
          $('#competencia_selecionada').bind('change', function() { goToPage(); } );
     });

   })

   function goToPage() {
    var baseUrl = '/agua/demonstrativo/';
    window.location.href = baseUrl + $('#competencia_selecionada').val()
   }

</script>
{% endblock %}

{% block content %}
<!-- you'll need jquery to make this work -->
  <h1>Demonstrativo</h1>
  <h2>Usuario Responsável - {{ user.username }}</h2>
  Selecione outra competência:
  <form>
    <select id="competencia_selecionada">
      <option value="{{competencia.simple}}" selected="true">{{competencia}}</option>
      {% for cpt in competencias %}
      <option value="{{cpt.simple}}">{{ cpt }}</option>
      {% endfor %}
    </select>
  </form>

  <h2>{{ competencia.extenso }}</h2>

  <table class="highlight">
    <thead>
      <tr>
        <th>Tipo despesa</th>
        <th>Descrição</th>
        <th>Data</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      {% for despesa in despesas %}
      <tr>
        <td>{{ despesa.tipo_despesa.descricao }}</td>
        <td>{{ despesa.descricao }}</td>
        <td>{{ despesa.data_despesa|date:"d.m.Y" }}</td>
        <td>{{ despesa.valor }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>
  <h2>Total  R$ {{ valor_total_despesa }}</h2>
  <h2>Por Hidrômetro:</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Identificao Hidrömetro</th>
        <th>Consumo</th>
        <th>Percentual</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
<!--
      hidrometro = models.ForeignKey(Hidrometro, on_delete=models.CASCADE)
      data_medicao = models.DateField()
      cmpt = models.ForeignKey(Competencia, on_delete=models.PROTECT,null=True)
      medicao = models.DecimalField(max_digits=8, decimal_places=3)
      consumo = models.DecimalField(max_digits=8, decimal_places=3)
-->
      {% for consumo in consumos %}
      <tr>
        <td>{{ consumo.0.hidrometro.condomino.nome_conhecido }}</td>
        <td>{{ consumo.0.hidrometro.identificacao }}</td>
        <td>{{ consumo.0.consumo }}</td>
        <td>{{ consumo.1|floatformat:2  }}</td>
        <td>{{ consumo.2|floatformat:2  }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>


  <h2>Por Condomino</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Consumo</th>
        <th>Percentual</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
<!--
      hidrometro = models.ForeignKey(Hidrometro, on_delete=models.CASCADE)
      data_medicao = models.DateField()
      cmpt = models.ForeignKey(Competencia, on_delete=models.PROTECT,null=True)
      medicao = models.DecimalField(max_digits=8, decimal_places=3)
      consumo = models.DecimalField(max_digits=8, decimal_places=3)
-->
      {% for consumo in consumo_por_condomino %}
      <tr>
        <td>{{ consumo.0 }}</td>
        <td>{{ consumo.1|floatformat:2  }}</td>
        <td>{{ consumo.2|floatformat:2  }}</td>
        <td>{{ consumo.3|floatformat:2  }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>


  <h2>Total Consumo: {{ total_consumo }} M3</h2>
  <br/>
  <br/>
{% endblock %}

src/aguaapp/templates/agua/demonstrativo.html
{% extends 'base.html' %}

{% block scripthead %}
<script type="text/javascript">
   $(document).ready(function() {
     $(function() {
          // navigate to page on click event
          $('#competencia_selecionada').bind('change', function() { goToPage(); } );
     });

   })

   function goToPage() {
    var baseUrl = '/agua/demonstrativo/';
    window.location.href = baseUrl + $('#competencia_selecionada').val()
   }

</script>
{% endblock %}

{% block content %}
<!-- you'll need jquery to make this work -->
  <h1>Demonstrativo</h1>
  <h2>Usuario Responsável - {{ user.username }}</h2>
  Selecione outra competência:
  <form>
    <select id="competencia_selecionada">
      <option value="{{competencia.simple}}" selected="true">{{competencia}}</option>
      {% for cpt in competencias %}
      <option value="{{cpt.simple}}">{{ cpt }}</option>
      {% endfor %}
    </select>
  </form>

  <h2>{{ competencia.extenso }}</h2>

  <table class="highlight">
    <thead>
      <tr>
        <th>Tipo despesa</th>
        <th>Descrição</th>
        <th>Data</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      {% for despesa in despesas %}
      <tr>
        <td>{{ despesa.tipo_despesa.descricao }}</td>
        <td>{{ despesa.descricao }}</td>
        <td>{{ despesa.data_despesa|date:"d.m.Y" }}</td>
        <td>{{ despesa.valor }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>
  <h2>Total  R$ {{ valor_total_despesa }}</h2>
  <h2>Por Hidrômetro:</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Identificao Hidrömetro</th>
        <th>Consumo</th>
        <th>Percentual</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
<!--
      hidrometro = models.ForeignKey(Hidrometro, on_delete=models.CASCADE)
      data_medicao = models.DateField()
      cmpt = models.ForeignKey(Competencia, on_delete=models.PROTECT,null=True)
      medicao = models.DecimalField(max_digits=8, decimal_places=3)
      consumo = models.DecimalField(max_digits=8, decimal_places=3)
-->
      {% for consumo in consumos %}
      <tr>
        <td>{{ consumo.0.hidrometro.condomino.nome_conhecido }}</td>
        <td>{{ consumo.0.hidrometro.identificacao }}</td>
        <td>{{ consumo.0.consumo }}</td>
        <td>{{ consumo.1|floatformat:2  }}</td>
        <td>{{ consumo.2|floatformat:2  }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>


  <h2>Por Condomino</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Consumo</th>
        <th>Percentual</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
<!--
      hidrometro = models.ForeignKey(Hidrometro, on_delete=models.CASCADE)
      data_medicao = models.DateField()
      cmpt = models.ForeignKey(Competencia, on_delete=models.PROTECT,null=True)
      medicao = models.DecimalField(max_digits=8, decimal_places=3)
      consumo = models.DecimalField(max_digits=8, decimal_places=3)
-->
      {% for consumo in consumo_por_condomino %}
      <tr>
        <td>{{ consumo.0 }}</td>
        <td>{{ consumo.1|floatformat:2  }}</td>
        <td>{{ consumo.2|floatformat:2  }}</td>
        <td>{{ consumo.3|floatformat:2  }}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>


  <h2>Total Consumo: {{ total_consumo }} M3</h2>
  <br/>
  <br/>
{% endblock %}

src/aguaapp/templates/agua/home.html
{% extends 'base.html' %}


{% block content %}
  <h2>Usuario Responsável - {{ user.username }}</h2>
  <div>
  </div>
  <ul>
    <li><a href="{% url 'agua:demonstrativo'  %}">Demonstrativo</a></li>
  </ul>
  <h2>Unidades</h2>
  {% for l in listaHidrometros %}
    <h3>{{ l.0.condominio.nome }}</h3>
    <h4>{{ l.0.nome_conhecido }}</h4>
    {% if  l.1 %}
      <h5>Hidrômetros</h5>
      <table border="1">
        <thead>
          <tr>
            <th>Identificação</th>
            <th>Data da última Medição</th>
            <th>Competëncia</th>
            <th>Valor</th>
            <th>Ação</th>
          </tr>
        </thead>
        <tbody>
          {% for h in l.1 %}
            <tr>
              <td>{{ h.identificacao }}</td>
              <td>{{ h.ultima_medicao.data_medicao|date:"d/m/Y" }}</td>
              <td>{{ h.ultima_medicao.cmpt }}</td>
              <td>{{ h.ultima_medicao.medicao }}</td>
              <td><a href="/agua/consumo/{{ h.id }}"><span class="glyphicon glyphicon-scale"/> Informar consumo</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  {% endfor %}
  <br/>
  <br/>
{% endblock %}